### ISSUE TITLE
No pr model

### ISSUE THREAD

**Issue by DaHaiHuha** [mswzeus/PLUS#1]
Hi, thanks for your great work!
However, I could not find a pre-trained pr_model for evaluation tasks. Is there anything wrong? Besides, I used the pre-trained P-ELMO and lm model. When I assigned the pr model to 'P-ELMo_Homology.pt', I got wrong message like below:
```
Missing key(s) in state_dict: "hidden.weight", "hidden.bias", "output.weight", "output.bias". 
Unexpected key(s) in state_dict: "x_embed.weight", "fc_lm.weight", "fc_lm.bias", "rnn.weight_ih_l0", "rnn.weight_hh_l0", "rnn.bias_ih_l0", "rnn.bias_hh_l0", "rnn.weight_ih_l0_reverse", "rnn.weight_hh_l0_reverse", "rnn.bias_ih_l0_reverse", "rnn.bias_hh_l0_reverse", "rnn.weight_ih_l1", "rnn.weight_hh_l1", "rnn.bias_ih_l1", "rnn.bias_hh_l1", "rnn.weight_ih_l1_reverse", "rnn.weight_hh_l1_reverse", "rnn.bias_ih_l1_reverse", "rnn.bias_hh_l1_reverse", "rnn.weight_ih_l2", "rnn.weight_hh_l2", "rnn.bias_ih_l2", "rnn.bias_hh_l2", "rnn.weight_ih_l2_reverse", "rnn.weight_hh_l2_reverse", "rnn.bias_ih_l2_reverse", "rnn.bias_hh_l2_reverse", "fc.weight", "fc.bias", "ordinal_weight", "ordinal_bias". 
```
Should I train a pr model myself? Thanks!

**Comment by seonwoo-min** [comment]
Hi,
Thanks for your interest in our work!

We have uploaded all the codes and pre-trained model weights to reproduce the results.
I think you need to check a few things if you got some error messages.

(1) 
Have you downloaded a pre-trained (or fine-tuned) model from our webpage?
As stated in the README, you can download the model weights from our website (http://ailab.snu.ac.kr/PLUS/).
If you are interested in using P-ELMo for the Homology task, click [Homology] link from the "Fine-tuned" category.

(2)
Once you have downloaded the pre-trained model, you need to provide correct arguments for the Python script. The arguments set model configurations and load pre-trained weights from the provided files. More explanation of each argument is provided in each Python script.
For example, you can use the below command to evaluate P-ELMo for the Homology task.

<pre><code>
python eval_plus_homology.py --data-config config/data/homology.json --model-config config/model/p-elmo.json --lm-model-config config/model/p-elmo_lm.json  --run-config config/run/p-elmo_homology.json --pretrained-model pretrained_models/P-ELMo_Homology.pt --pretrained-lm-model pretrained_models/P-ELMo_lm.pt --output-path results/ --device 0 
</pre></code>
If you have any other questions or problems, just let me know!

**Comment by DaHaiHuha** [comment]
@mswzeus Thank you, Seonwoo! It's so kind of you to provide such clear explanation! The PLUS work is  very great. 

However, I actually meet some trouble when I tend to fill in those arguments, because the same [optional] arguments are provided for both train/eval scripts. And I'm not not clearly understand when the pr (project layer I think?) is needed? 

Besides, I downloaded the pre-trained model and there is a `*_cm.pt` model, could you please tell what is that used for?

Thanks!!

**Comment by seonwoo-min** [comment]
No problem, @DaHaiHuha!

Although a number of same arguments both for train/eval scripts could be confusing, they were necessary to provide usage flexibility for users. If it were not for the arguments, we'd have to provide different versions of (almost identical) scripts for each model (e.g. PLUS-RNN, PLUS-TFM, and P-ELMo). If you have other good ideas for the code organization, I'm all ears!

**Simply put, a pr_model is required for the train/eval of protein-level and amino-acid-level tasks.**
The fine-tuning procedure of PLUS is different for each type of downstream tasks.
For protein-level and amino-acid-level tasks, we add two layers (hidden and output layer) on top of the pre-trained model. The added layers are referred to as pr-model (prediction) in the provided codes. In contrast, for protein-pair-level tasks, since we directly compare their representations with soft-alignment, we do not need pr-models. 

The _cm.pt model is for "contact map prediction" which is used as an auxiliary pre-training task in P-ELMo. (For PLUS, we do not use the contact map prediction.) If you want to evaluate contact map prediction performance for the Homology task, you can use the provided cm_model. Otherwise, you can disregard it and the other files are enough to obtain structural similarity prediction performance for the Homology task.

You can find more detailed explanations in our paper (https://arxiv.org/abs/1912.05625).

**Comment by DaHaiHuha** [comment]
Thank you! Now the code's logic is clear.
But what if I want to train a P-ELMo with "contact map prediction" task so that I could get a P-ELMo model trained with multi-tasks? I could not find a scripts suitable for training this model.

**Comment by seonwoo-min** [comment]
You can use <code>train_plus_homology.py</code> file. It supports training P-ELMo model with or without "contact map prediction".

**Please note that our paper and codes are mainly for **PLUS** (our proposed model).**
If you are more interested in **P-ELMo**, I think you would find its official repository more useful.
(https://github.com/tbepler/protein-sequence-embedding-iclr2019)

**Comment by DaHaiHuha** [comment]
@mswzeus Thank you for your kind reminder and your great work! Now I'm going to close the issue.
